apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/kubeflow-oteam/jupyter-web-app-frontend
        name: jupyter-web-app
        ports:
        - containerPort: 4000
